services:
  mojo-app:
    build: .
    ports:
      - "8080:3000"
    volumes:
      - .:/app
    command: morbo -l http://0.0.0.0:3000 -w /app/full_mojo_app full_mojo_app/script/full_mojo_app
    depends_on:
      app-db:
        condition: service_healthy
      render-api:
        condition: service_started
    environment:
      DB_DSN: "mariadb://appuser:${APP_DB_PASSWORD}@app-db:3306/webwork_gui"
      RENDER_API_URL: "http://render-api:3000"

  app-db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: ${APP_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: webwork_gui
      MYSQL_USER: appuser
      MYSQL_PASSWORD: ${APP_DB_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - app_db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10

  render-api:
    build:
      context: ./render-api-src
    ports:
      - "3000:3000"
    environment:
      - MOJO_MODE=production
    # volumes:
    # - ./:/usr/app/public/test:ro
    restart: unless-stopped

volumes:
  app_db_data:
